text_skin: default  # Change "default" to another color scheme if you want (e.g., "forest", "ocean").
highlight_theme: default  # Leave this or choose another highlight theme for code blocks.

url: https://awdygus.github.io  # Set your website URL.
baseurl:  # Leave this blank unless your site is hosted in a subdirectory.
title: Agnieszka Dygus's Website  # Set your site's title.
description: > 
  Welcome to my personal website! I am a Philosophy PhD student specializing in Metaphysics and Epistemology.

author:
  type: person
  name: Agnieszka Dygus
  url: https://awdygus.github.io
  bio: Philosophy PhD student specializing in Metaphysics and Epistemology.
  email: adygus@ur.rochester.edu
  linkedin: www.linkedin.com/in/agnieszka-dygus
  github: awdygus  # Your GitHub username.

repository: awdygus/awdygus.github.io
repository_tree: master  # Keep "master" unless your default branch is named differently (e.g., "main").
paginate: 8  # The number of posts per page.
paginate_path: /page:num  # Path for paginated pages.
comments:
  provider: false  # Set to "disqus" if you want comments and provide your Disqus shortname below.
  disqus:
    shortname: your-disqus-id
search:
  provider: default  # Keep "default" unless you want to use a custom search engine.
